/*
 * ConnectBot: simple, powerful, open-source SSH client for Android
 * Copyright 2026 Kenny Root
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package solutions.ormus.logos.commands

/**
 * The slash commands each agent ships with, most used first. The descriptions
 * are agent data in the agents' own language (English), like the command names.
 *
 * Sources (read 2026-10-04):
 * - Claude Code 2.1.289: code.claude.com/docs/en/commands.md ("All commands"),
 *   names checked against the installed binary. /todos is not a command in this
 *   version (its task list is /tasks); hidden /heapdump is left out.
 * - Codex: codex-rs/tui/src/slash_command.rs on openai/codex main (popup order
 *   and description strings), arguments from learn.chatgpt.com developer-commands.
 *   Debug-build-only commands are left out.
 * - Grok 1.0.46: ~/.grok/docs/user-guide/04-slash-commands.md on Sun (the same
 *   text ships in the binary); /help and /recap from the binary's strings.
 *
 * An [SlashCommand.argumentHint] marks a command whose argument is the point
 * (a path, a question, a goal), so a tap puts it in the dictation field. Commands
 * whose argument is optional and rarely given carry no hint, so a tap runs them;
 * a long press in the menu puts any command in the field.
 */
object SlashCatalogs {
    fun forAgent(agent: AgentKind): List<SlashCommand> = when (agent) {
        AgentKind.CLAUDE -> CLAUDE
        AgentKind.CODEX -> CODEX
        AgentKind.GROK -> GROK
    }

    private fun c(name: String, description: String, hint: String? = null) = SlashCommand(name, description, hint)

    val CLAUDE: List<SlashCommand> = listOf(
        c("clear", "New conversation with empty context (also /reset, /new)"),
        c("compact", "Summarize the conversation to free context"),
        c("model", "Switch model and save it as the default"),
        c("resume", "Resume a session by name, or open the picker (also /continue)"),
        c("review", "Review the diff or a PR for correctness bugs (alias of /code-review)"),
        c("init", "Create a starter CLAUDE.md"),
        c("memory", "Edit CLAUDE.md and auto memory"),
        c("config", "Settings panel (also /settings)"),
        c("cost", "Cost, plan limits and activity stats (alias of /usage)"),
        c("status", "Settings panel on the Status tab"),
        c("help", "Help and the command list"),
        c("agents", "Create or manage subagents"),
        c("mcp", "Manage MCP connections and OAuth"),
        c("permissions", "Allow, ask and deny rules (also /allowed-tools)"),
        c("add-dir", "Add a working directory for this session", "<path>"),
        c("doctor", "Setup checkup that can fix issues (also /checkup)"),
        c("export", "Export the conversation as plain text"),
        c("hooks", "View hook configurations"),
        c("rewind", "Roll conversation and/or code back to a point (also /undo)"),
        c("tasks", "Background work, including finished subagents (the old /todos)"),
        c("context", "Context usage grid"),
        c("plan", "Enter plan mode"),
        c("effort", "Set effort from low to max, or auto"),
        c("usage", "Cost, plan limits and activity stats (also /stats)"),
        c("code-review", "Review the diff or a PR for correctness bugs"),
        c("diff", "Review working-tree changes"),
        c("btw", "Side question that is not added to history", "[question]"),
        c("goal", "Keep working until a condition is met", "[condition]"),
        c("loop", "Repeat a prompt while the session is open", "[interval] [prompt]"),
        c("rename", "Rename the session"),
        c("copy", "Copy the last reply"),
        c("skills", "List skills"),
        c("recap", "One-line summary of the session"),
        c("security-review", "Security review of the branch changes"),
        c("simplify", "Cleanup pass on changed code"),
        c("subtask", "Forked subagent; its result comes back here", "<task>"),
        c("fork", "Copy the conversation into a new background session"),
        c("branch", "Branch the conversation at this point"),
        c("background", "Detach the session to run as a background agent (also /bg)"),
        c("cd", "Move the session to another directory", "<path>"),
        c("advisor", "Turn the advisor that consults a second model on or off"),
        c("artifacts", "List your artifacts; attach, open or copy a link"),
        c("auto-mode-setup", "Draft autoMode.environment entries and save them"),
        c("autocompact", "Set how full context gets before auto-compact"),
        c("autofix-pr", "Cloud session that pushes fixes for CI or review comments"),
        c("batch", "Large parallel change across the codebase in worktrees", "<instruction>"),
        c("bug", "Report a bug or share the conversation (also /share)"),
        c("chrome", "Claude in Chrome settings"),
        c("claude-api", "Claude API and Managed Agents reference"),
        c("claude-in-chrome", "Run a task in your browser", "[task]"),
        c("color", "Set the prompt bar color"),
        c("dataviz", "Guidance for charts and dashboards"),
        c("debug", "Turn on debug logging and troubleshoot"),
        c("deep-research", "Fan-out web research with a cited report", "<question>"),
        c("design", "UI mockups as a Claude Design artifact"),
        c("design-login", "Authorize design-system access"),
        c("design-sync", "Upload the repo's React design system to Claude Design"),
        c("desktop", "Continue in the Desktop app (also /app)"),
        c("exit", "Exit the CLI (also /quit)"),
        c("fast", "Toggle fast mode"),
        c("feedback", "Send product feedback"),
        c("fewer-permission-prompts", "Build an allowlist from your transcripts"),
        c("focus", "Focus view (fullscreen renderer only)"),
        c("ide", "IDE integrations and status"),
        c("import", "Import config from Codex, Gemini CLI or Cursor"),
        c("insights", "HTML report on your recent sessions"),
        c("install-github-app", "Install the Claude GitHub App"),
        c("install-slack-app", "Install the Claude Slack app"),
        c("keybindings", "Open the keybindings file"),
        c("list-agents", "List subagents and sessions Claude can message"),
        c("login", "Sign in to your Anthropic account"),
        c("logout", "Sign out of your Anthropic account"),
        c("mobile", "QR code for the mobile app"),
        c("output-style", "List or switch output styles"),
        c("passes", "Share a free week with friends"),
        c("plugin", "Manage plugins"),
        c("plugin-authoring", "Reference for writing a mod"),
        c("powerup", "Interactive feature lessons"),
        c("privacy-settings", "Privacy settings"),
        c("radio", "Open Claude FM in the browser"),
        c("rate-limit-options", "Options when a usage limit blocks you"),
        c("release-notes", "Changelog version picker"),
        c("reload-plugins", "Reload plugins without restarting"),
        c("reload-skills", "Re-scan skill and command directories"),
        c("remote-control", "Expose the session to claude.ai Remote Control (also /rc)"),
        c("remote-env", "Default cloud environment"),
        c("run", "Launch and drive the app"),
        c("run-skill-generator", "Teach /run and /verify how to launch your project"),
        c("sandbox", "Toggle sandbox mode"),
        c("schedule", "Cloud routines (also /routines)"),
        c("scroll-speed", "Mouse wheel speed"),
        c("setup-bedrock", "Amazon Bedrock auth wizard"),
        c("setup-vertex", "Google Vertex auth wizard"),
        c("skill-doctor", "Context cost and usage of each skill"),
        c("slides", "Make a Claude Slides deck"),
        c("statusline", "Configure the status line"),
        c("stickers", "Order stickers"),
        c("stop", "Stop the attached background session"),
        c("team-onboarding", "Team onboarding guide from your usage"),
        c("teleport", "Pull a cloud session into this terminal (also /tp)"),
        c("terminal-setup", "Install the Shift+Enter newline binding"),
        c("theme", "Color theme"),
        c("tui", "Set the renderer and relaunch"),
        c("ultrareview", "Multi-agent cloud review"),
        c("update-config", "Edit settings.json from a description", "[request]"),
        c("upgrade", "Plan upgrade page"),
        c("usage-credits", "Usage credits"),
        c("verify", "Build, run and observe the change"),
        c("voice", "Voice dictation"),
        c("web-setup", "Connect GitHub for cloud sessions"),
        c("workflow-authoring", "Reference for workflow scripts"),
        c("workflows", "Workflow progress view"),
        c("artifact-capabilities", "Reference for artifact runtime capabilities"),
        c("artifact-diagramming", "Diagram guidance for artifacts"),
    )

    val CODEX: List<SlashCommand> = listOf(
        c("model", "Choose what model and reasoning effort to use"),
        c("new", "Start a new chat during a conversation"),
        c("clear", "Clear the terminal and start a new chat"),
        c("compact", "Summarize conversation to prevent hitting the context limit"),
        c("resume", "Resume a saved chat"),
        c("review", "Review my current changes and find issues"),
        c("status", "Show current session configuration and token usage"),
        c("diff", "Show git diff (including untracked files)"),
        c("init", "Create an AGENTS.md file with instructions for Codex"),
        c("permissions", "Choose what Codex is allowed to do"),
        c("plan", "Switch to Plan mode"),
        c("goal", "Set or view the goal for a long-running task", "[objective]"),
        c("btw", "Start a side conversation in an ephemeral fork", "[text]"),
        c("side", "Start a side conversation in an ephemeral fork", "[text]"),
        c("mcp", "List MCP tools"),
        c("skills", "Use skills to improve how Codex performs specific tasks"),
        c("agents", "Open the agent command center"),
        c("subagents", "Switch between this session's subagents"),
        c("usage", "View account usage or use a usage limit reset"),
        c("copy", "Copy the last response or part of it"),
        c("recap", "Summarize the current conversation now"),
        c("fork", "Fork the current chat"),
        c("rename", "Rename the current thread"),
        c("cd", "Change the current working directory", "<path>"),
        c("pwd", "Show the current working directory"),
        c("mention", "Mention a file"),
        c("ide", "Include selection, open files and other IDE context"),
        c("worktree", "Start or continue a conversation in a new worktree"),
        c("export", "Export the conversation as markdown"),
        c("approve", "Approve one retry of a recent auto-review denial"),
        c("hooks", "View and manage lifecycle hooks"),
        c("memories", "Configure memory use and generation"),
        c("experimental", "Toggle experimental features"),
        c("import", "Import setup, this project and recent chats from Claude Code"),
        c("keymap", "Remap TUI shortcuts"),
        c("vim", "Toggle Vim mode for the composer"),
        c("raw", "Toggle raw scrollback mode for copy-friendly selection"),
        c("tui", "Choose the TUI mode for the next launch"),
        c("theme", "Choose a syntax highlighting theme"),
        c("statusline", "Configure which items appear in the status line"),
        c("title", "Configure which items appear in the terminal title"),
        c("voice", "Start or stop voice"),
        c("daybreak", "Turn Daybreak on or off"),
        c("ps", "List background terminals"),
        c("stop", "Stop all background terminals (also /clean)"),
        c("daemon", "Manage the local background server"),
        c("warnings", "View retained warnings and diagnostic details"),
        c("debug-config", "Show config layers and requirement sources"),
        c("apps", "Manage apps"),
        c("plugins", "Browse plugins"),
        c("pets", "Choose or hide the terminal pet"),
        c("archive", "Archive this session"),
        c("delete", "Permanently delete this session"),
        c("app", "Continue this session in the Desktop app"),
        c("setup-default-sandbox", "Set up elevated agent sandbox (Windows)"),
        c("feedback", "Send logs to maintainers"),
        c("logout", "Log out of Codex"),
        c("quit", "Exit Codex (also /exit)"),
    )

    val GROK: List<SlashCommand> = listOf(
        c("new", "Fresh session, clears the conversation (also /clear)"),
        c("compact", "Compress history to free context"),
        c("model", "Switch model (also /m)"),
        c("resume", "Session picker"),
        c("context", "Context window breakdown"),
        c("session-info", "Auth, model, turn count, context usage (also /status)"),
        c("help", "Browse commands and keyboard shortcuts"),
        c("plan", "Enter plan mode"),
        c("view-plan", "Preview the saved plan"),
        c("rewind", "Roll back to an earlier turn (also /undo)"),
        c("fork", "Branch the session into a new agent"),
        c("effort", "Reasoning effort for the current model", "<low|medium|high|xhigh>"),
        c("always-approve", "Toggle skipping all permission prompts"),
        c("auto", "Toggle auto-review"),
        c("btw", "Side question without interrupting", "<question>"),
        c("goal", "Autonomous goal", "<objective>"),
        c("loop", "Recurring prompt", "[interval] <prompt>"),
        c("deep-research", "Background verified research", "<query>"),
        c("remember", "Save a note to memory", "<note>"),
        c("memory", "Browse and manage memories (also /mem)"),
        c("flush", "Save session knowledge to memory now"),
        c("dream", "Consolidate memory"),
        c("recap", "Summarize the session so far"),
        c("copy", "Copy the last reply, or write it to a file"),
        c("export", "Export the conversation to a file or the clipboard"),
        c("rename", "Rename the session", "<title>"),
        c("skills", "Skills tab"),
        c("hooks", "Extensions modal, Hooks tab"),
        c("plugins", "Plugins tab"),
        c("marketplace", "Marketplace tab"),
        c("mcps", "MCP servers modal"),
        c("workflows", "Saved workflow catalog"),
        c("workflow", "Launch or manage workflows"),
        c("dashboard", "Agent Dashboard (also /sessions)"),
        c("history", "Fuzzy-search past prompts"),
        c("imagine", "Generate an image", "<description>"),
        c("imagine-video", "Generate a video", "<description>"),
        c("context-window", "Context window size", "<size>"),
        c("multiline", "Toggle multiline input (also /ml)"),
        c("edit-prompt", "Open \$EDITOR for the prompt"),
        c("compact-mode", "Denser display"),
        c("vim-mode", "Vim scrollback keys"),
        c("minimal", "Switch to the minimal renderer"),
        c("fullscreen", "Switch to the fullscreen renderer (also /full)"),
        c("timestamps", "Toggle message timestamps"),
        c("theme", "Color theme (also /t)"),
        c("doctor", "Terminal, clipboard and sandbox checks"),
        c("docs", "How-to guides (also /howto)"),
        c("release-notes", "Release notes (also /changelog)"),
        c("tutorial", "Onboarding (also /tour)"),
        c("import-claude", "Import ~/.claude settings"),
        c("config-agents", "Agent definitions (also /agents)"),
        c("personas", "Create and edit personas"),
        c("usage", "Credit usage and billing (also /cost)"),
        c("privacy", "Coding-data opt-in or opt-out"),
        c("settings", "Settings modal (also /config)"),
        c("feedback", "Feedback form, or send the message directly"),
        c("home", "Back to the welcome screen"),
        c("delete", "Delete this session's history"),
        c("login", "Sign in"),
        c("logout", "Sign out"),
        c("quit", "Quit (also /exit)"),
    )
}
